#!/bin/bash

init() {
  REMOTE_REPO=`echo "$1" | cut -d"/" -f 5`
  SERVER=`echo "$2" | cut -d"/" -f 1 | cut -d"@" -f 2 | cut -d":" -f 1`
  ORG=`echo "$2" | cut -d"/" -f 1 | cut -d"@" -f 2 | cut -d":" -f 2`
  REPO=`echo "$2" | cut -d"/" -f 2`
  echo "mirror to: $SERVER $ORG $REPO"
  git clone --bare $1
  cd $REMOTE_REPO
  git lfs fetch --all
  git config lfs.https://$SERVER/$ORG/$REPO/info/lfs.locksverify true
  git remote set-url origin $2
  git lfs push --all
  git lfs push --all git@$2
  git lfs push --all origin
  git push --mirror
}

clone() {
  REMOTE_REPO=`echo "$1" | cut -d"/" -f 5`
  SERVER=`echo "$2" | cut -d"/" -f 1 | cut -d"@" -f 2 | cut -d":" -f 1`
  ORG=`echo "$2" | cut -d"/" -f 1 | cut -d"@" -f 2 | cut -d":" -f 2`
  REPO=`echo "$2" | cut -d"/" -f 2`
  DIR=`echo "$REPO" | cut -d"." -f 1`
  # Clone a local copy of our mirror and get assets from LFS
  git clone $2
  cd $DIR
  git lfs fetch --all

  # Fetch upstream changes including LFS
  git remote add upstream $1
  git remote update upstream
  git lfs fetch upstream --all

  # Setup our local git to track all branches so we can sync them
  # Solution from: https://stackoverflow.com/a/4754797/101258
  #for branch in $(git branch --all | grep '^\s*remotes' | egrep --invert-match '(:?HEAD|master)$'); do
  for branch in $(git for-each-ref --format='%(refname)' refs/remotes/upstream | cut -d'/' -f 4); do
      git branch --track "${branch##*/}" "$branch"
  done
  git fetch --all

  # Finally, push everything to our local Gitlab mirror
  git push origin --all
  git push origin --tags
}

update() {
  # Clone a local copy of our mirror and get assets from LFS
  git lfs fetch --all

  ## Fetch upstream changes including LFS
  git remote update upstream
  git lfs fetch upstream --all

  # Setup our local git to track all branches so we can sync them
  # Solution from: https://stackoverflow.com/a/4754797/101258
  #for branch in $(git branch --all | grep '^\s*remotes' | egrep --invert-match '(:?HEAD|master)$'); do
  for branch in $(git for-each-ref --format='%(refname)' refs/remotes/upstream | cut -d'/' -f 4); do
      echo "Track $branch"
      git branch --track "${branch##*/}" "$branch"
  done
  for branch in $(git for-each-ref --format='%(refname)' refs/heads/ | cut -d"/" -f 3); do
  #for branch in $(git branch); do
      # Attempt to pick up changes across all branches
      echo "Merge $branch"
      git checkout "$branch"
      git pull
      git merge upstream/"$branch"
  done
  git fetch --all

  ## Finally, push everything to our local Gitlab mirror
  git push origin --all
  git push origin --tags
}

case "$1" in
    init)
        init $2 $3
        ;;
    clone)
        clone $2 $3
        ;;
    update)
        update
        ;;
    *)
        cat << EOF
Usage: $0
TODO
EOF
        exit 1
esac

